---
# tasks file for wordpress
# WordPress Configuration
- name: create /var/www/{{ server_name }} directory for unarchiving
  become: yes
  become_method: sudo
  file:
    path: /var/www/{{ server_name }} 
    state: directory

- name: Download and unpack latest WordPress 
  become: yes
  become_method: sudo
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ server_name }}"
    remote_src: yes
    creates: "/var/www/{{ server_name }}/wordpress"

- name: Set ownership 
  become: yes
  become_method: sudo
  file:
    path: "/var/www/{{ server_name }}" 
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Set permissions for directories
  become: yes
  become_method: sudo
  shell: "/usr/bin/find /var/www/{{ server_name }}/wordpress/ -type d -exec chmod 750 {} \\;"

- name: Set permissions for files
  become: yes
  become_method: sudo
  shell: "/usr/bin/find /var/www/{{ server_name }}/wordpress/ -type f -exec chmod 640 {} \\;"

- name: Set up wp-config
  become: yes
  become_method: sudo
  copy:
    src: "./"
    dest: "/var/www/{{ server_name }}/wordpress/"