---
virtualmachines:
  hosts:
    gb-vm-01:
      ansible_host: 87.239.108.223
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /Users/alexandrpkhm/Documents/development/ssh/gb-vm-01-YltYUHtn.pem 